// <autogenerated>
//   This file was generated by T4 code generator Script1.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace Edo.Web.Template
{
	public class SampleClass
	{
		private string sampleField;

		public string SampleProperty { get; set; }
	}
}
