// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using Edo.Data.Entity.ComponentModel;
using Newtonsoft.Json;
using Edo.Data.Entity;
namespace Edo.ViewModels
{
    [Form("基本信息")]
    public partial class EmployeesViewModel : EntityBaseViewModel
    {
       
           
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("LastName")]
               public virtual String LastName { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("FirstName")]
               public virtual String FirstName { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("Title")]
               public virtual String Title { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("TitleOfCourtesy")]
               public virtual String TitleOfCourtesy { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("BirthDate")]
               public virtual DateTime? BirthDate { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("HireDate")]
               public virtual DateTime? HireDate { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("Address")]
               public virtual String Address { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("City")]
               public virtual String City { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("Region")]
               public virtual String Region { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("PostalCode")]
               public virtual String PostalCode { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("Country")]
               public virtual String Country { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("HomePhone")]
               public virtual String HomePhone { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("Extension")]
               public virtual String Extension { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("Photo")]
               public virtual Byte[] Photo { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("Notes")]
               public virtual String Notes { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("ReportsTo")]
               public virtual Int32? ReportsTo { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("PhotoPath")]
               public virtual String PhotoPath { get; set; }
                 
                                [JsonIgnore]
                 [Grid(ForeignKey ="EmployeeID")]
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("Orders")]
               public virtual  ICollection<Orders> Orders { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("CreatedDate")]
               public virtual DateTime CreatedDate { get; set; }
                  }
}
