// <autogenerated>
//   This file was generated by T4 code generator GenerateViewModel.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Edo.Data.Entity.ComponentModel;
using Newtonsoft.Json;
using Edo.Data.Entity;
namespace Edo.ViewModels
{
    [Form]
    public partial class OrderDetailsViewModel : EntityBaseViewModel
    {
       
                [GirdColumn(Hide=true, Field = "Orders.Id")]        
                [Required]
                [Select("Orders", "Id", "Id", "OrderID")]                  
                [DisplayName("Orders")]
                public virtual Guid OrderID { get; set; }

                [GirdColumn]                  
                [DisplayName("ProductName")]
                public virtual String ProductName { get; set; }

                [GirdColumn(Hide=true, Field = "Products.Id")]        
                [Required]
                [Select("Products", "Id", "Id", "ProductID")]                  
                [DisplayName("Products")]
                public virtual Guid ProductID { get; set; }

                [GirdColumn]                  
                [DisplayName("UnitPrice")]
                public virtual Decimal UnitPrice { get; set; }

                [GirdColumn]                  
                [DisplayName("Quantity")]
                public virtual Int16 Quantity { get; set; }

                [GirdColumn]                  
                [DisplayName("Discount")]
                public virtual Single Discount { get; set; }

            }
}
