// <autogenerated>
//   This file was generated by T4 code generator GenerateViewModel.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Edo.Data.Entity.ComponentModel;
using Newtonsoft.Json;
using Edo.Data.Entity;
namespace Edo.ViewModels
{
    public partial class OrderDetailsViewModel : EntityBaseViewModel
    {     
                  
                [DisplayName("OrderID")]
                public virtual Guid OrderID { get; set; }
          
                [DisplayName("ProductName")]
                public virtual String ProductName { get; set; }
          
                [DisplayName("ProductID")]
                public virtual Guid ProductID { get; set; }
          
                [DisplayName("UnitPrice")]
                public virtual Decimal UnitPrice { get; set; }
          
                [DisplayName("Quantity")]
                public virtual Int16 Quantity { get; set; }
          
                [DisplayName("Discount")]
                public virtual Single Discount { get; set; }
  
                [JsonIgnore]          
                [DisplayName("Orders")]
                public virtual Orders Orders { get; set; }
  
                [JsonIgnore]          
                [DisplayName("Products")]
                public virtual Products Products { get; set; }
   }
}
 