// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using Edo.Data.Entity.ComponentModel;
using Newtonsoft.Json;
using Edo.Data.Entity;
namespace Edo.ViewModels
{
    [Form("基本信息")]
    public partial class OrdersViewModel : EntityBaseViewModel
    {


        [GirdColumn(Sortable = true, Width = 100)]
        [DisplayName("OrderDate")]
        public virtual DateTime? OrderDate { get; set; }

        [GirdColumn(Sortable = true, Width = 100)]
        [DisplayName("RequiredDate")]
        public virtual DateTime? RequiredDate { get; set; }

        [GirdColumn(Sortable = true, Width = 100)]
        [DisplayName("ShippedDate")]
        public virtual DateTime? ShippedDate { get; set; }

        [GirdColumn(Sortable = true, Width = 100)]
        [DisplayName("ShipVia")]
        public virtual Int32? ShipVia { get; set; }

        [GirdColumn(Sortable = true, Width = 100)]
        [DisplayName("Freight")]
        public virtual Decimal? Freight { get; set; }

        [GirdColumn(Sortable = true, Width = 100)]
        [DisplayName("ShipName")]
        public virtual String ShipName { get; set; }

        [GirdColumn(Sortable = true, Width = 100)]
        [DisplayName("ShipAddress")]
        public virtual String ShipAddress { get; set; }

        [GirdColumn(Sortable = true, Width = 100)]
        [DisplayName("ShipCity")]
        public virtual String ShipCity { get; set; }

        [GirdColumn(Sortable = true, Width = 100)]
        [DisplayName("ShipRegion")]
        public virtual String ShipRegion { get; set; }

        [GirdColumn(Sortable = true, Width = 100)]
        [DisplayName("ShipPostalCode")]
        public virtual String ShipPostalCode { get; set; }

        [GirdColumn(Sortable = true, Width = 100)]
        [DisplayName("ShipCountry")]
        public virtual String ShipCountry { get; set; }

        [JsonIgnore]
        [Grid(ForeignKey = "OrderID")]
     //   [GirdColumn(Sortable = true, Width = 100)]
        [DisplayName("OrderDetails")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }

        [GirdColumn(Sortable = true, Width = 100)]
        [DisplayName("CreatedDate")]
        public virtual DateTime CreatedDate { get; set; }
    }
}
