// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using Edo.Data.Entity.ComponentModel;
using Newtonsoft.Json;
using Edo.Data.Entity;
namespace Edo.ViewModels
{
    [Form("基本信息")]
    public partial class ProductsViewModel : EntityBaseViewModel
    {
       
           
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("ProductName")]
               public virtual String ProductName { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("QuantityPerUnit")]
               public virtual String QuantityPerUnit { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("UnitPrice")]
               public virtual Int16? UnitPrice { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("UnitsInStock")]
               public virtual Int16? UnitsInStock { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("UnitsOnOrder")]
               public virtual Int16? UnitsOnOrder { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("ReorderLevel")]
               public virtual Int16? ReorderLevel { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("Discontinued")]
               public virtual Boolean Discontinued { get; set; }
                 
                                [JsonIgnore]
                 [Grid(ForeignKey ="ProductID")]
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("OrderDetails")]
               public virtual  ICollection<OrderDetails> OrderDetails { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("CreatedDate")]
               public virtual DateTime CreatedDate { get; set; }
                  }
}
