// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using Edo.Data.Entity.ComponentModel;
using Newtonsoft.Json;
using Edo.Data.Entity;
namespace Edo.ViewModels
{
    [Form("基本信息")]
    public partial class ShippersViewModel : EntityBaseViewModel
    {
       
           
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("CompanyName")]
               public virtual String CompanyName { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("Phone")]
               public virtual String Phone { get; set; }
                 
                                [JsonIgnore]
                 [Grid(ForeignKey ="ShipperID")]
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("Orders")]
               public virtual  ICollection<Orders> Orders { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("CreatedDate")]
               public virtual DateTime CreatedDate { get; set; }
                  }
}
