// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using Edo.Data.Entity.ComponentModel;
using Newtonsoft.Json;
using Edo.Data.Entity;
namespace Edo.ViewModels
{
    [Form("基本信息")]
    public partial class SuppliersViewModel : EntityBaseViewModel
    {
       
           
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("CompanyName")]
               public virtual String CompanyName { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("ContactName")]
               public virtual String ContactName { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("ContactTitle")]
               public virtual String ContactTitle { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("Address")]
               public virtual String Address { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("City")]
               public virtual String City { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("Region")]
               public virtual String Region { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("PostalCode")]
               public virtual String PostalCode { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("Country")]
               public virtual String Country { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("Phone")]
               public virtual String Phone { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("Fax")]
               public virtual String Fax { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("HomePage")]
               public virtual String HomePage { get; set; }
                 
                                [JsonIgnore]
                 [Grid(ForeignKey ="SupplierID")]
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("Products")]
               public virtual  ICollection<Products> Products { get; set; }
                 
                              [GirdColumn(Sortable = true, Width = 100)]        
               [DisplayName("CreatedDate")]
               public virtual DateTime CreatedDate { get; set; }
                  }
}
