// <autogenerated>
//   This file was generated by T4 code generator GenerateViewModel.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Edo.Data.Entity.ComponentModel;
using Newtonsoft.Json;
using Edo.Data.Entity;
namespace Edo.ViewModels
{
    public partial class UserViewModel : EntityBaseViewModel
    {     
                  
                [DisplayName("Name")]
                public virtual String Name { get; set; }
          
                [DisplayName("Password")]
                public virtual String Password { get; set; }
          
                [DisplayName("Address")]
                public virtual String Address { get; set; }
  
                [JsonIgnore]          
                [DisplayName("Roles")]
                public virtual  ICollection<RoleViewModel> Roles { get; set; }
   }
}
 