// <auto-generated />
namespace QuickZ.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addRole));
        
        string IMigrationMetadata.Id
        {
            get { return "201609170753470_addRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
