// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Edo.Data.Entity;
using System.Data.Entity;
using Edo.ViewModels;
using System.Linq.Dynamic.Core;
using Edo.Service;
using System.Threading.Tasks;
namespace Edo.Web.Controllers
{
    public partial class CustomersController : BaseController<Customers, CustomersViewModel>
    {
        public CustomersController(BaseService<Customers> service)
            : base(service)
        {

        }
        public ActionResult Index()
        {
            return View();
        }
        public async Task<ActionResult> PageRegion(string itemFilter, int pageIndex, int pageSize, string sort, string filter)
        {
            var obj = _dbset.Where(itemFilter).SelectMany(p => p.Regions);
            return await PageData<Region, RegionViewModel>(obj, sort, filter, pageIndex, pageSize);
        }
        public async Task<ActionResult> Select2Region(string itemFilter, string field, string q)
        {
            var obj = await _dbset.Where(itemFilter).FirstOrDefaultAsync();
            if (obj == null) return HttpNotFound();
            return await SelectData(obj.Regions.AsQueryable(), field, q);
        }
    }
}
