// <autogenerated>
//   This file was generated by T4 code generator GenerateController.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Edo.Data.Entity;
using Edo.Data.Entity.ComponentModel;
using Edo.ViewModels;
using System.Linq.Dynamic.Core;
using Edo.Service;
using System.Threading.Tasks;
namespace Edo.Web.Controllers
{
	public partial class UserRoleController : BaseController<UserRole, UserRoleViewModel>
	{
        public UserRoleController(BaseService<UserRole> service)
        :base(service)
        {
       
        }
        public ActionResult Index()
        {
            return View();
        }
       	}
}
